# Generated by Django 4.0.5 on 2023-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0002_url_status_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='session',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
